<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bpm/bpm.jquery.zebra-stripe.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	$('.stripe').bpm_stripe();
    $('.message_head').click(function() {
        $(this).next('.message_body').slideToggle(500);
        return false;
    });

    $('#newProjectButton').click(function() {
        $('#newProjectDialog').dialog('open');
    });

    $('#newProjectDialog').dialog({
        bgiframe:   true,
        autoOpen:   false,
        modal:      true,
        width:      350,
        buttons:    {
            'Add Project':  function() {
                $.ajax({
                    data:   {
                        projectName:        $('#projectName').val(),
                        projectDescription: $('#projectDescription').val()
                    },
                    dataType:   'json',
                    success:    function(rsp, status) {
                        if(rsp.status == 1) {
                            window.location = '<?php echo $this->baseUrl(); ?>';
                        } else {
                            alert('There was a problem adding the project. Please contact tech support.');
                        }
                    },
                    type:       'POST',
                    url:        '<?php echo $this->baseUrl();?>/projects/add'
                });
            }
        }
    });
});
</script>

<h1>Current Projects</h1>

<table width="100%" class="stripe">
	<thead>
		<tr>
			<th>Project Name</th>
			<th>Description</th>
			<th width="100px">Actions</th>
		</tr>
	</thead>
	<tbody>
	<?php if(count($this->projects)): ?>
	    	<?php foreach($this->projects as $project): ?>
			<?php if($project->status < 10): ?>
		    		<tr>
		    			<td><a href="<?php echo $this->baseUrl(); ?>/projects/load/project/<?php echo $project->id; ?>"><?php echo $project->name; ?></a></td>
		    			<td><?php echo $project->description; ?></td>
		    			<td align="center"><a href="<?php echo $this->baseUrl(); ?>/projects/load/project/<?php echo $project->id; ?>">View</a></td>
				</tr>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php else: ?>
		<tr>
			<td colspan="3" align="center"><b>You are not part of any projects</b></td>
		</tr> 
	<?php endif; ?>
	</tbody>
</table>

<button id="newProjectButton" style="float: right">Add Project</button>

<div id="newProjectDialog" title="Add New Project" class="left">
    <dl>
        <dt>Project Name:</dt>
            <dd><input type="text" name="projectName" id="projectName"></dd>
        <dt>Project Description:</dt>
            <dd><textarea style="height: 200px; width: 300px" name="projectDescription" id="projectDescription"></textarea>
    </dl>
</div>
