<h1>Available Reports</h1>

<table width="100%">
	<thead>
		<tr>
			<th>Report Name</th>
			<th>Description</th>
			<th>Run</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Projects by User</td>
			<td>Displays the number and list of projects a user is associated with</td>
			<td align="center"><a href="<?php echo $this->baseUrl(); ?>/admin/reports/pbu"><img src="<?php echo $this->baseUrl(); ?>/images/famfamfam_silk/report.png"></a></td>
		</tr>
		<tr>
			<td>Project List With Description</td>
			<td>Lists all the approved and unsubmitted projects with description, author, and priority</td>
			<td align="center"><a href="<?php echo $this->baseUrl(); ?>/admin/reports/plwd"><img src="<?php echo $this->baseUrl(); ?>/images/famfamfam_silk/report.png"></a></td>
		</tr>
	</tbody>
</table>
