<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Biff ProjectManager</title>

    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/redmond/jquery-ui-1.7.custom.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/yui-2.7.0/reset-fonts-grids/reset-fonts-grids.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/layout/color.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/layout/layout.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/layout/type.css" type="text/css">

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-ui-1.7.custom.min.js"></script>
</head>
<body class="tundra">
<div id="doc3" class="yui-t7">
    <div id="hd">
        <div style="float: right; color: white">
            <a href="<?php echo $this->baseUrl(); ?>/admin">Admin</a> |
            <a href="<?php echo $this->baseUrl(); ?>/auth/index/logout">Log Out</a>
        </div>
        <h1><a href="<?php echo $this->baseUrl(); ?>/">GMIC Project Manager</a></h1>
    </div>
    <div id="bd">
        <div class="yui-g" id="content">
            <!-- Main Content -->
            <?php echo $this->layout()->content; ?>
        </div>
    </div>	
</div>
</body>
</html>
